
title: More on why pugs are the best
author: Grace 
email: gmadlinger@github.com
description: > # this means to ignore newlines until "baseurl:"
  Pugs are literally the best dog in the world. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
